server:
  port: 8088
  servlet:
    context-path: /

spring:
  application:
    name: dlyk-sever

  # 数据库配置
  datasource:
    url: jdbc:mysql://192.168.159.134:3306/dlyk?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  # redis配置
  data:
    redis:
      host: 192.168.159.134
      port: 6379
      password: 123456
      database: 0

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志配置
logging:
  level:
    root: INFO
  file:
    name: dlyk-sever.log
  logback:
    rolling-Policy:
      max-file-size: 100MB
      total-size-cap: 50GB
      max-history: 60
      clean-history-on-start: false
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz


# 自定义配置
dlyk:
  jwt:
    secret: ajoiepf@efs5ef5e5

